# -*- coding: utf-8 -*-
"""if-else_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FEfUcZ4C62JfKaURs9DRQI8ILb9loO_
"""

def chatbot():
    print("Hello! I'm a simple chatbot. How can I help you today?")

    while True:
        user_input = input("You: ").lower()
        if user_input in ["hi", "hello", "hey"]:
            print("Chatbot: Hello! How can I assist you?")

        elif user_input in ["how are you?", "how are you", "what's up?"]:
            print("Chatbot: I'm just a program, but thanks for asking! How can I help you?")

        elif user_input in ["what is your name?", "who are you?"]:
            print("Chatbot: I'm a simple chatbot created to assist you.")

        elif user_input in ["bye", "exit", "quit"]:
            print("Chatbot: Goodbye! Have a great day!")
            break
        else:
            print("Chatbot: I'm sorry, I don't understand that. Can you ask something else?")


if __name__ == "__main__":
    chatbot()

